Milestone 5 - Freindships_v1
Zubenna/ror-social-scaffold pull request #2
Opened 2020-10-15 12:50 UTC by Zubenna

2020-10-18 19:50 UTC, adaorachi requested changes
### Hi @Zubenna and @umairarshadbutt :wave: 
You've done quite a good job on this project. And I also commend your effort for updating your README to reflect the current features in your app. Well done! :+1: 
However, there some changes you'll need to make in order to get your project approved.

---
### STATUS: REQUIRES CHANGES :recycle: 

---

- [ ] I noticed you have the Stickler linter enabled in your project. You are only required to use the Github action for lining your code. Kindly disable Stickler for this project and delete its files from your project.

- [x] In your README, kindly include that `rails db:create` is needed to be run in order to create the database.

- [ ] Still in the README, the `How to Test the Project` subtitle should be best written as `Project SetUp/Installation` to avoid confusing it with the Run Test section. In addition, I'm sure there are two collaborators to this project, kindly include the social handle links of the second collaborator in the Authors section.

- [ ] Your test suite has three failed tests in the `spec/features/friendship_spec.rb` file. Kindly fix them.

- [ ] You posts timeline should include posts written by logged-in user and their friends. Currently, a user can see all posts from all users. Kindly get it fixed. Here's a [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from pathwright.

- [ ] Lastly, there is a weird behavior I noticed from your friend request feature. When I unfriend a user, the button text for another user changes instead. I attached a GIF below to show that. Kindly see it and ensure that you get to fix the issue.

![Peek 2020-10-18 20-33](https://user-images.githubusercontent.com/50773261/96378216-6140f600-1182-11eb-90a6-b7f46fe0684f.gif)


### After implementing the changes above, you can request for another code review.

Should you have any question, do reach out to me on Slack with the username @adaorachi

Happy Coding :relaxed: 

MaryAnn Chukwuka

2020-10-20 04:39 UTC, voscarmv requested changes
# Impressive work, team! 🖥️ 👀 ✨ 

- Good work applying the changes requested earlier.

## However, some changes are still required... 🧰 🔨 🔧 

- Please add proper linter configuration for this project. You may find the instructions on how to do this here: https://github.com/microverseinc/linters-config/tree/master/ror

- You seem to only be testing successful cases in your `spec` files. Please take some time to consider negative (failed) test cases as well for your app features. Read my code comments to better understand what I mean.

**[OPTIONAL]**

- It's always nice to have a live version, on heroku for example, to showcase your project. Please consider adding a live version on your project, and also adding a link to it on your README.

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-10-20 04:39 UTC, voscarmv commented on spec/features/comment_spec.rb
> +end
In this test you only test for a successful outcome of creating a comment. Please add negative cases for this and all other cases. That is: produce an error output when creating a message by creating an invalid message, and confirm the error message through rspec.

Please remember to add this same kind of test for all other features in your app.

2020-10-20 07:29 UTC, Zubenna commented on spec/features/comment_spec.rb
> +end
# Requested changes have been implemented. Kindly note the following
## - Please run all tests separately as stated in the readme.md file and in my response to the last reviewer's feedback at least twice to avoid ambiguity.
## - Live demo link will be added after the last milestone. App has not been hosted on Heroku yet.

2020-10-20 09:45 UTC, voscarmv requested changes
# Nice work so far, team. 👍 

- Thank you for applying the changes I requested earlier.

## However, there are some changes required 👀 🧰 🔨 🔧 

I've found a bug while testing your code on my local environment. Try going through the following steps to reproduce this bug yourselves:

1. Drop the database in order to create a new one with `rails db:drop`
2. Create a new database with `rails db:create`
3. Add the tables with `rails db:migrate`
4. Create a user `User1` and write a comment.
5. Log out and create a new user `User2` and create a comment.
6. Send a friend request to `User1` by clicking `Add user` from the user list.
7. Log out and login as `User1` and click on `Accept` from the user list.

Here's where the bug happens: once the user list refreshes after clicking `Accept`, it should show `Unfriend`, but instead it just shows `Add friend` next to `User2` instead.

This seems to only happen for the first friend request, because all following requests and acceptances work fine. This bug only appears when the database is freshly created, so make sure to drop your database and create it again as specified in my instructions to reproduce the bug. Please fix this!

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-10-20 17:55 UTC, kubilaycaglayan requested changes
#### Hello Team 👋
#### Status: Changes Required ♻️

Great job so far! 👏👋
The project is amazing but the bug seems to be still there 😊⏬

### Bug
![bug_social](https://user-images.githubusercontent.com/60448833/96624623-a9dce880-1315-11eb-8b9b-07655c56891e.png)

- [ ]  Please fix the bug 🐛

I see that you created the "unfriend" link. But what missing is, in the helper method "confirm_friendship_button" is referring to the `friendship_button` and it hits the second case on the flow logic.

👉 Please work on the `friends?` instance method in the User class.

## That's it, you can request another code review request after making the changes ♻️😇

With all my respect 🙏
> Kubilay Caglayan | Technical Support Engineer

2020-10-20 17:55 UTC, kubilaycaglayan commented on app/models/user.rb
> +  end
:bulb: Try this method in `rails c` with different scenarios. Is it working as you are expecting?

2020-10-21 01:03 UTC, Ispirett requested changes
### Changes Required !!

This is great work so far folks and I can see you are working really hard on this. 👍  👍 

- [ ] 10 of your  20 tests are failing.
- [ ] After adding a friend the friend can add me. I'm sure this will be fix in version 2 of friendships

2020-10-21 05:40 UTC, maelfosso approved these changes
# Congratulations :clap: 

Thank you for making the suggested changes :+1: 
You can merge it now :blush: 

Good continuation :handshake: 

Mael FOSSO

2020-10-21 05:40 UTC, maelfosso commented on app/views/users/_pending.html.erb
> +  <% end %>
**OPTIONAL**
Can you please, remove logic from view and move it into view helpers?

2020-10-21 14:49 UTC, merged